### ISSUE TITLE
Multiple meal plans generated with same meals

### ISSUE THREAD

**Issue by cdm319** [cdm319/macro-meal-planner#4]
The current implementation allows multiple meal plans to be generated with duplicate meals, if they're in reverse order, i.e.
```json
[
    ["Breakfast A", "Main B", "Main C", "Snack D"],
    ["Breakfast A", "Main C", "Main B", "Snack D"]
]
```

**Comment by nickmcblain** [comment]
Had a think about this and the only quick thing I could come up with was ordering the meals based on name and creating a match key by concatenating the names and comparing them to dedupe.

**Comment by cdm319** [comment]
Implemented Set of hashed meal names to dedupe 👍
